name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build DogStatsd.Extensions.Hosting/DogStatsd.Extensions.Hosting.csproj --no-restore --configuration Release
    - name: Publish
      uses: laget-se/publish-nuget@v2.7.2
      with:
        INCLUDE_SYMBOLS: true
        PROJECT_FILE_PATH: DogStatsd.Extensions.Hosting/DogStatsd.Extensions.Hosting.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        NUSPEC_FILE: DogStatsd.Extensions.Hosting.nuspec
        VERSION_STATIC: "1.2.${{github.run_number}}"
